### ISSUE TITLE
Docker Issues Windows

### ISSUE THREAD

**Issue by monkeydust** [8090-inc/xrx-sample-apps#6]
Trying to docker build on windows. 

Used this command: C:\Users\admin\Github\xrx-sample-apps\patient-information-app>docker-compose up --build

Gor this error

` => ERROR [xrx-client builder 2/2] RUN npm run build                                                                                             11.6s
 => [xrx-tts] resolving provenance for metadata file                                                                                              0.1s
 => [xrx-stt] resolving provenance for metadata file                                                                                              0.0s
 => [xrx-reasoning] resolving provenance for metadata file                                                                                        0.0s
------
 > [xrx-client builder 2/2] RUN npm run build:
0.801
0.801 > nextjs-client@0.1.0 prebuild
0.801 > cd ../xrx-core/react-xrx-client && npm install && npm run build
0.801
4.328
4.328 added 9 packages, and audited 10 packages in 3s
4.329
4.329 found 0 vulnerabilities
4.465
4.465 > react-xrx-client@0.1.0 build
4.465 > tsc
4.465
5.705
5.705 > nextjs-client@0.1.0 build
5.705 > next build
5.705
6.212 Attention: Next.js now collects completely anonymous telemetry regarding usage.
6.212 This information is used to shape Next.js' roadmap and prioritize features.
6.212 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
6.212 https://nextjs.org/telemetry
6.212
6.263   ▲ Next.js 14.2.3
6.264
6.319    Creating an optimized production build ...
11.34 Failed to compile.
11.34
11.35 ./src/app/page.tsx
11.35 Module not found: Can't resolve './components/pre-interaction-widget/PreInteractionComponent'
11.35
11.35 https://nextjs.org/docs/messages/module-not-found
11.35
11.35
11.35 > Build failed because of webpack errors
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1`

**Comment by sabbyanandan** [comment]
@monkeydust: Sorry that you're having trouble with it on Windows. We will have a look and get back to you shortly.

**Comment by im007** [comment]
` => ERROR [xrx-client builder 2/2] RUN npm run build                                                                           31.4s
------
 > [xrx-client builder 2/2] RUN npm run build:
1.011
1.011 > nextjs-client@0.1.0 prebuild
1.011 > cd ../xrx-core/react-xrx-client && npm install && npm run build
1.011
4.173
4.173 added 9 packages, and audited 10 packages in 3s
4.176
4.176 found 0 vulnerabilities
4.579
4.579 > react-xrx-client@0.1.0 build
4.579 > tsc
4.579
9.339
9.339 > nextjs-client@0.1.0 build
9.339 > next build
9.339
11.36 Attention: Next.js now collects completely anonymous telemetry regarding usage.
11.36 This information is used to shape Next.js' roadmap and prioritize features.
11.36 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
11.36 https://nextjs.org/telemetry
11.36
11.60   ▲ Next.js 14.2.3
11.60
11.85    Creating an optimized production build ...
30.41 Failed to compile.
30.41
30.41 ./src/app/page.tsx
30.41 Module not found: Can't resolve './components/pre-interaction-widget/PreInteractionComponent'
30.41
30.41 https://nextjs.org/docs/messages/module-not-found
30.41
30.41
30.41 > Build failed because of webpack errors
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1`
Tested on Windows, confirming the npm run build error. We are working on a solution.
